<<<<<<< HEAD
title : API Voice
=======
title : API Evangelist
>>>>>>> df7ceab2ef4ae3d50219904b2b7c038552e9c828

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

<<<<<<< HEAD
source: api-voice
destination: api-voice
=======
source: 101
destination: 101
>>>>>>> df7ceab2ef4ae3d50219904b2b7c038552e9c828

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 10
paginate_path: "/blog/page:num"

<<<<<<< HEAD
production_url : http://apivoice.com

BASE_PATH : http://apivoice.com
=======
production_url : http://101.apievangelist.com

BASE_PATH : http://101.apievangelist.com
>>>>>>> df7ceab2ef4ae3d50219904b2b7c038552e9c828

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
